進入帳號管理頁面
Game-as-a-Service/Lobby-Platform pull request #48
Opened 2023-05-05 12:54 UTC by lohas1107

## Why need this change? / Root cause: 
- As a user, I want to see my user information.
## Changes made:
- New Feature: Get user
## Test Scope / Change impact:
- UserController
## Issue
- resolved #34

2023-05-05 15:52 UTC, frankvicky requested changes

2023-05-05 15:52 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
> +    override fun createUser(user: User): User = userDAO.save(UserData.toData(user)).toDomain()
`UserData.toData(user)` 可以使用擴充改寫成 `User.toData()`

2023-05-05 15:55 UTC, Johnny850807 requested changes
Review done

2023-05-05 15:55 UTC, Johnny850807 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/repositories/UserRepository.kt
> +    fun findUserById(id: String): User?
使用 UserId instead of id primitive type `fun findUserById(id: UserId): User?`
所以可以一定程度地將 primitive type 的變動隔離開

2023-05-05 15:55 UTC, Johnny850807 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserUseCase.kt
> +    fun execute(id: String) = userRepository.findUserById(id)
`fun execute(id: UserId) = userRepository.findUserById(id)`

2023-05-05 15:55 UTC, Johnny850807 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/controllers/UserController.kt
> +    fun getUser(@PathVariable id: String) = getUserUseCase.execute(id)
如果 `getUserUseCase.execute(id)` return null 要轉換成丟 404 response

2023-05-05 15:55 UTC, Johnny850807 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/SpringUserRepository.kt
> +    override fun findUserById(id: String): User? = userDAO.findById(id).orElse(null)?.toDomain()
change to:
 `userDAO.findById(id).map(UserData::toDomain).orElse(null)`

2023-05-05 15:55 UTC, Johnny850807 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/UserControllerTest.kt
> +    private fun whenGetUser(id: String): ResultActions = mockMvc.perform(get("/users/$id"))
suggestion: rename to `findUserById` or `whenGetUserById`

由於未來可能會在多個測資中重複使用到這個方法好幾次，所以我自己不會以 when 作為前綴，避免在其他測資中以為測項是 Get User by Id。我會使用比較通泛的 `findUserById` 說法

2023-05-05 15:55 UTC, Johnny850807 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/UserControllerTest.kt
> +    }
轉成 extension method (kotlin 真棒)

```kotlin fun ResultActions.thenUserNotFound() {
    this.andExpect(status().isOk)
        .andExpect(jsonPath("$.id").doesNotExist())
        .andExpect(jsonPath("$.email").doesNotExist())
        .andExpect(jsonPath("$.nickname").doesNotExist())
}
```

所以，`givenUserNotCreated_whenGetUser_thenUserNotFound` 可以改寫成：

```kotlin
@Test
    fun givenUserNotCreated_whenGetUser_thenUserNotFound() {
        whenGetUser("0")
            .thenUserNotFound()
    }
```

2023-05-05 15:55 UTC, Johnny850807 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/UserControllerTest.kt
> +    }
轉成 extension method (kotlin 真棒)

```kotlin
fun ResultActions.thenGetUserSuccessfully(user: User) {
    this.andExpect(status().isOk)
        .andExpect(jsonPath("$.id").value(user.id!!.value))
        .andExpect(jsonPath("$.email").value(user.email))
        .andExpect(jsonPath("$.nickname").value(user.nickname))
}
```

所以，`givenUserCreated_whenGetUser_thenGetUserSuccessfully ` 可以改寫成：

```kotlin
@Test
fun givenUserCreated_whenGetUser_thenGetUserSuccessfully() {
        val user = User(User.UserId("1"), "test@mail.com", "winner5566")
        givenUserCreated(user)
        whenGetUser("1")
            .thenGetUserSuccessfully(user)
}
```

2023-05-06 00:29 UTC, lohas1107 commented
@ricksu978 @frankvicky 第一次 push 自己的分支到 remote 後，就不能再 push 第二次了，請協助調整保護分支的設定
錯誤訊息：`remote: error: GH006: Protected branch update failed for refs/heads/feature/get-user.`

2023-05-06 04:22 UTC, ricksu978 commented
> @ricksu978 @frankvicky 第一次 push 自己的分支到 remote 後，就不能再 push 第二次了，請協助調整保護分支的設定 錯誤訊息：`remote: error: GH006: Protected branch update failed for refs/heads/feature/get-user.`

@lohas1107 不好意思，權限相關設定已修正，麻煩再測試一下。

2023-05-06 04:22 UTC, frankvicky commented
> @ricksu978 @frankvicky 第一次 push 自己的分支到 remote 後，就不能再 push 第二次了，請協助調整保護分支的設定 錯誤訊息：`remote: error: GH006: Protected branch update failed for refs/heads/feature/get-user.`

午安，目前權限 @ricksu978  已經調整過了，麻煩你再試試看

2023-05-06 10:08 UTC, lohas1107 commented
@ricksu978 @frankvicky 成功 push了
@Johnny850807 @frankvicky 按照建議調整完程式，再麻煩 review

2023-05-06 10:47 UTC, Johnny850807 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserUseCase.kt
> +    fun execute(id: String) = userRepository.findUserById(id)
@lohas1107 這個好像還沒有改

2023-05-06 10:50 UTC, Johnny850807 requested changes
Review done

2023-05-06 10:50 UTC, Johnny850807 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/UserNotFoundException.kt
> +class UserNotFoundException(id: User.UserId) : Throwable() {
繼承 `RuntimeException`

2023-05-06 10:50 UTC, Johnny850807 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/UserNotFoundException.kt
> +class UserNotFoundException(id: User.UserId) : Throwable() {
類別可以改名為 NotFoundException
因為未來每一種 resource 應該都會有 not found 的 case
我們不用為每一個 case 宣告一種 NotFoundException 👍

2023-05-06 10:53 UTC, frankvicky requested changes

2023-05-06 10:53 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/UserData.kt
> +    }
若是採用擴充就不用包裹在 `companion object` 之中。
另外使用擴充時我們可以在 function block 取得擴充類別的 context，所以這裡不需要再用 `with(this)`。

2023-05-06 11:51 UTC, lohas1107 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/UserNotFoundException.kt
> +class UserNotFoundException(id: User.UserId) : Throwable() {
已調整

2023-05-06 11:51 UTC, lohas1107 commented on domain/src/main/kotlin/tw/waterballsa/gaas/exceptions/UserNotFoundException.kt
> +class UserNotFoundException(id: User.UserId) : Throwable() {
已調整

2023-05-06 11:51 UTC, lohas1107 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/repositories/data/UserData.kt
> +    }
已調整

2023-05-06 12:48 UTC, frankvicky approved these changes
LGTM

2023-05-06 15:11 UTC, Johnny850807 approved these changes
還有一個小 comment

不過改完就可以當作 LGTM 囉！ gogo!

2023-05-06 15:11 UTC, Johnny850807 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserUseCase.kt
> +    fun execute(id: String): User {
`fun execute(id: UserId) = userRepository.findUserById(id)`

這個還沒有改唷～
希望 controller 傳進來的時候就包成 UserId 了

2023-05-06 22:24 UTC, lohas1107 commented on application/src/main/kotlin/tw/waterballsa/gaas/application/usecases/GetUserUseCase.kt
> +    fun execute(id: String): User {
@Johnny850807 改好囉～

2023-05-07 05:49 UTC, merged