GitHub Action CI / CD
Game-as-a-Service/Lobby-Platform pull request #57
Opened 2023-05-10 01:11 UTC by ricksu978

## Why need this change? / Root cause: 
We need CI/CD, so that developers can see actual swagger document at https://api.gaas.waterballsa.tw/swagger-ui/index.html

## Changes made:
- Added EventBus mock
- Added build-and-deploy.yml
- Added pull_request_template.md
- Fixed Embedded Mongodb Issue

## Test Scope / Change impact:
- Commit pushed to `feature/*` branch will only trigger `build` (no deploy)
- PR merged to `main` branch will trigger both `build` and `deploy`

2023-05-10 01:37 UTC, Wally5077 requested changes
Review done.

2023-05-10 01:37 UTC, Wally5077 commented on spring/pom.xml
> +        <finalName>Lobby-Platform</finalName>
Q1：這有辦法從環境變數設定嗎？
Q2：承上題，如果可以是不是就能由 CI 的 `JAR_FILE_NAME` 設定了呢？

2023-05-10 01:37 UTC, Wally5077 commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/eventbus/WebSocketEventBus.kt
> +@Named
如果是在 Spring 層，用 `@Component` 就好，直接和框架耦合也沒關係

2023-05-10 01:37 UTC, Wally5077 commented on spring/src/test/kotlin/tw/waterballsa/gaas/spring/controllers/WalkingSkeletonControllerTest.kt
> +    @MockBean
這可以改成 `@Autowired`
先前用 `@MockBean`，是因為還沒有 EventBus 的實作類，所以 Spring 無法注入才用的

2023-05-10 01:37 UTC, Wally5077 requested changes
Review done.

2023-05-10 01:55 UTC, frankvicky requested changes
Review done.

2023-05-10 01:55 UTC, frankvicky commented on spring/src/main/kotlin/tw/waterballsa/gaas/spring/eventbus/WebSocketEventBus.kt
> +        TODO("Not yet implemented")
這邊 TODO 方法改為 TODO 註解
使用 TODO 方法在執行時會拋出 `NotImplementedError`

2023-05-11 05:41 UTC, Wally5077 approved these changes
LGTM

2023-05-11 06:03 UTC, merged